name: data_ai_chatbpt
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.4.10
  hooks_riverpod: ^2.4.10
  langchain: ^0.4.2
  langchain_openai: ^0.4.1
  langchain_pinecone: ^0.0.7
  path_provider: ^2.1.2
  pinecone: ^0.7.2
  riverpod_annotation: ^2.3.4
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9
  sqflite: ^2.3.2
  syncfusion_flutter_pdf: ^24.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/pdf/
    - .env